apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adventurewiki-ingress
  namespace: {{ .Values.ingress.namespace }}
spec:
  entryPoints:                      # [1]
    - websecure
  routes:                           # [2]
    - kind: Rule
      match: Host(`{{ .Values.ingress.domain }}`)
      priority: 10
      services:
        - name: adventurewiki
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.wiki.service.port }}
  tls:                              # [12]
    secretName: {{ .Values.ingress.certificate.secretName }}