apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.clusterName }}
spec:
  teamId: adventurewiki
  volume:
    size: 8Gi
  numberOfInstances: 1
  users:
    # database owner
    root:
    - login
    - superuser
    - createdb
    adventurewikiuser:
    - login

  #databases: name->owner
  databases:
    adventurewiki: adventurewikiuser
  postgresql:
    version: "15"