apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adventurewiki-postgres-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: adventurewiki-postgres-certificate-secret
  dnsNames:
    - {{ include "debenstack-adventurewiki.fullname" . }}
  issuerRef:
    name: {{ .Values.ingress.certificate.issuer | default "letsencrypt-dev-cluster-issuer" }}
    kind: ClusterIssuer